config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#feed"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/users/:id", to: "users#profile", as: "user"
  get "/users/:id/friends", to: "users#friends", as: "friends"

  get "/users/:id/delete_friend", to: "users#delete_friend", as: "delete_friend"
  get "/users/:id/cancel_friend_invite", to: "users#cancel_friend_invite", as: "cancel_friend_invite"
  get "/users/:id/invite_friend", to: "users#invite_friend", as: "invite_friend"
  get "/users/:id/accept_friend_request", to: "users#accept_friend_request", as: "accept_friend_request"
  get "/users/:id/decline_friend_request", to: "users#decline_friend_request", as: "decline_friend_request"

  get "/people", to: "static_pages#people"
  get "/feed", to: "static_pages#feed"
  get "/about", to: "static_pages#about"

  resources :posts, only: [:new, :create, :show]
  post "/posts/:id/create_comment", to: "posts#create_comment", as: "create_comment"
  get "/posts/:id/toggle_like", to: "posts#toggle_like", as: "toggle_like"

  get "/dialogs/", to: "dialogs#index"
  get "/dialogs/:id", to: "dialogs#show", as: "dialog"
  post "/dialogs/:id/create_message", to: "dialogs#create_message", as: "create_message"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def people
    join_statement = <<~SQL
         LEFT JOIN friendships f ON
      f.friend_id = users.id OR f.other_friend_id = users.id
    SQL
    where_statement = <<~SQL
      users.id NOT IN (
          SELECT u.id
          FROM users as u
                   INNER JOIN friendships f2 ON
                  (f2.friend_id = u.id OR f2.other_friend_id = u.id)
                  AND (f2.friend_id = #{current_user.id} OR f2.other_friend_id = #{current_user.id})
      ) AND users.id <> #{current_user.id}
    SQL
    @people = User.joins(join_statement).where(where_statement).group('id').order('COUNT(users.id)')
  end

  def feed
    posts = Post.distinct.includes(:author).joins(friends_children_join('posts')).order('created_at DESC')
    comments = Comment.distinct.includes(:author, :post)
                      .joins(friends_children_join('comments')).order('created_at DESC')
    # @type [Array<Post,Comment>]
    @feed = (posts + comments).sort_by!(&:created_at).reverse
  end

  def about; end

  private

  def friends_children_join(table)
    <<~SQL
      INNER JOIN users f ON
            #{table}.author_id = f.id AND f.id <> #{current_user.id}
      INNER JOIN friendships f_join ON
            (f_join.friend_id = f.id OR f_join.other_friend_id = f.id)
        AND (f_join.friend_id = #{current_user.id} OR f_join.other_friend_id = #{current_user.id})
    SQL
  end
end

app/views/static_pages/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light p-2">
  <div class="container">
    <a class="navbar-brand" href="/">Agora</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Feed", feed_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%
            friend_requests = current_user.friend_request_count
            text = "Friends" + (friend_requests == 0 ? '' : " (+#{friend_requests})")
          %>
          <%= link_to text, friends_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "People", people_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", dialogs_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    <div class="d-flex">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/static_pages/about.html.erb
<div class="container bg-light shadow-sm rounded my-3 py-3">
  <h5>Created by VanDeGraf</h5>
  <hr>
  <h6><a href="https://github.com/VanDeGraf/odin-agora">GitHub</a></h6>
  <h6>
    <a href="https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/rails-final-project">TheOdinProject</a>
  </h6>
</div>

app/views/static_pages/feed.html.erb
<% unless @feed.empty? %>
  <% @feed.each do |feed_item| %>
    <% if feed_item.is_a?(Post) %>
      <%= render "posts/post", post: feed_item, show_author: true %>
    <% elsif feed_item.is_a?(Comment) %>
      <%= render "posts/comment", comment: feed_item, show_parent: true %>
    <% end %>
  <% end %>
<% end %>

app/views/static_pages/people.html.erb
<% unless @people.empty? %>
  <div class="container bg-light rounded shadow-sm py-2">
    <h2>People</h2>
    <div class="list-group">
      <% @people.each do |user| %>
        <%= render "users/friendlist_item", friend: user %>
      <% end %>
    </div>
  </div>
<% end %>