config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#feed"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/users/:id", to: "users#profile", as: "user"
  get "/users/:id/friends", to: "users#friends", as: "friends"

  get "/users/:id/delete_friend", to: "users#delete_friend", as: "delete_friend"
  get "/users/:id/cancel_friend_invite", to: "users#cancel_friend_invite", as: "cancel_friend_invite"
  get "/users/:id/invite_friend", to: "users#invite_friend", as: "invite_friend"
  get "/users/:id/accept_friend_request", to: "users#accept_friend_request", as: "accept_friend_request"
  get "/users/:id/decline_friend_request", to: "users#decline_friend_request", as: "decline_friend_request"

  get "/people", to: "static_pages#people"
  get "/feed", to: "static_pages#feed"
  get "/about", to: "static_pages#about"

  resources :posts, only: [:new, :create, :show]
  post "/posts/:id/create_comment", to: "posts#create_comment", as: "create_comment"
  get "/posts/:id/toggle_like", to: "posts#toggle_like", as: "toggle_like"

  get "/dialogs/", to: "dialogs#index"
  get "/dialogs/:id", to: "dialogs#show", as: "dialog"
  post "/dialogs/:id/create_message", to: "dialogs#create_message", as: "create_message"
end

app/models/user.rb
class User < ApplicationRecord
  require 'open-uri'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :confirmable, :trackable

  has_many :friendships,
           ->(user) { unscope(:where).where('friend_id = ? OR other_friend_id = ?', user.id, user.id) },
           dependent: :destroy
  has_one_attached :avatar
  has_many :posts, class_name: 'Post', foreign_key: 'author_id', inverse_of: :author, dependent: :destroy
  has_and_belongs_to_many :liked,
                          class_name: 'Post',
                          join_table: 'likes',
                          foreign_key: 'user_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id', inverse_of: :author, dependent: :destroy
  has_many :sent_messages, class_name: 'Message', foreign_key: :sender_id,
           inverse_of: :sender, dependent: :destroy
  has_many :received_messages, class_name: 'Message', foreign_key: :recipient_id,
           inverse_of: :recipient, dependent: :destroy

  def grouped_friendships(invite: false)
    groups = {
      friend: [],
      invited: [],
      requested: []
    }
    if invite
      friendships.find_each do |friendship|
        groups[friendship.friendship_status(self)] << friendship
      end
    else
      friendships.where(invite: false).find_each do |friendship|
        groups[:friend] << friendship
      end
    end
    groups
  end

  def friendship_status(user)
    return nil if self == user

    status = nil
    friendships.find_each do |friendship|
      unless (status = friendship.friendship_status(user)).nil?
        return case status
               when :invited
                 :requested
               when :requested
                 :invited
               else
                 status
               end
      end
    end
    status
  end

  def friend_request_count
    Friendship.where(other_friend_id: id, invite: true).count
  end

  # @return [ActiveRecord::Relation]
  def interlocutors
    join_statement = <<~SQL
      INNER JOIN users ON
            users.id = messages.recipient_id OR users.id = messages.sender_id
    SQL
    where_statement = <<~SQL
      (messages.recipient_id = #{id} OR messages.sender_id = #{id})
        AND users.id <> #{id}
    SQL
    User.reselect('users.*').from('messages').joins(join_statement).unscope(:where).where(where_statement)
        .group('users.id').sort_by(&:created_at).reverse
  end

  # @param interlocutor_id [Integer] - user id
  def dialog_messages(interlocutor_id)
    join_statement = <<~SQL
      INNER JOIN users ON
            users.id = messages.recipient_id OR users.id = messages.sender_id
    SQL
    where_statement = <<~SQL
        (messages.recipient_id = #{id} AND messages.sender_id = #{interlocutor_id})
      OR (messages.sender_id = #{id} AND messages.recipient_id = #{interlocutor_id})
    SQL
    Message.distinct.joins(join_statement).unscope(:where).where(where_statement).sort_by(&:created_at)
  end

  def sex_name
    case sex
    when 1
      'female'
    when 2
      'male'
    else
      ''
    end
  end

  def representative_name
    name = "#{first_name} #{last_name}"
    name = email if name.length <= 1

    name.chomp
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.confirmed_at = DateTime.now.prev_day
      user.password = Devise.friendly_token[0, 20]
      user.birthday = Date.parse(auth.extra.raw_info.birthday) unless auth.extra.raw_info.birthday.nil?
      user.first_name = auth.extra.raw_info.first_name
      user.last_name = auth.extra.raw_info.last_name
      user.sex = case auth.extra.raw_info.sex
                 when 'male'
                   2
                 when 'female'
                   1
                 else
                   0
                 end
      unless auth.extra.raw_info.is_avatar_empty
        avatar_url = "https://avatars.yandex.net/get-yapic/#{auth.extra.raw_info.default_avatar_id}/islands-middle"
        user.attach_avatar_from_url(avatar_url)
      end
    end
  end

  def attach_avatar_from_url(url)
    file = URI.open(url)
    avatar.attach(io: file,
                  filename: "temp.#{file.content_type_parse.first.split('/').last}",
                  content_type: file.content_type_parse.first)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def yandex
      @user = User.from_omniauth(request.env['omniauth.auth'])
      sign_in_and_redirect @user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    # @type [User]
    @user = User.includes(:posts).find(params[:id])
  end

  def friends
    # @type [User]
    @user = User.find(params[:id])
    @friendships = @user.grouped_friendships(invite: @user == current_user)
  end

  def delete_friend
    fs = Friendship.intersection(current_user.id, params[:id].to_i).first
    if fs.nil?
      flash[:notice] = 'Error when try removing User from friend list'
    else
      fs.destroy
      flash[:notice] = 'User removed from friend list'
    end
    redirect_back fallback_location: '/'
  end

  def cancel_friend_invite
    fs = Friendship.intersection(current_user.id, params[:id].to_i).first
    if fs.nil?
      flash[:notice] = 'Error when try removing User from friend invites list'
    else
      fs.destroy
      flash[:notice] = 'User removed from friend invites list'
    end
    redirect_back fallback_location: '/'
  end

  def invite_friend
    fs = Friendship.intersection(current_user.id, params[:id].to_i).first
    if fs.nil?
      Friendship.create(invite: true, friend_id: current_user.id, other_friend_id: params[:id].to_i)
      flash[:notice] = 'User invited to yours friend list'
    else
      flash[:notice] = 'Error when try User invite to yours friend list'
    end
    redirect_back fallback_location: '/'
  end

  def accept_friend_request
    fs = Friendship.intersection(current_user.id, params[:id].to_i).first
    if fs.nil?
      flash[:notice] = 'Error when try User add to yours friend list'
    else
      fs.invite = false
      fs.save
      flash[:notice] = 'User added to yours friend list'
    end
    redirect_back fallback_location: '/'
  end

  def decline_friend_request
    fs = Friendship.intersection(current_user.id, params[:id].to_i).first
    if fs.nil?
      flash[:notice] = 'Error when try removing User from friend request list'
    else
      fs.destroy
      flash[:notice] = 'User friend request declined'
    end
    redirect_back fallback_location: '/'
  end
end

app/views/users/_friendlist_item.html.erb
<div class="d-flex">
  <% href = defined?(url) ? url : user_url(friend) %>
  <a href="<%= href %>" class="list-group-item list-group-item-action d-flex">
    <div class="border border-secondary rounded-circle overflow-hidden" style="width: 4rem; height: 4rem;">
      <%= image_tag friend.avatar if friend.avatar.attached? %>
    </div>
    <div class="mx-3">
      <h5><%= friend.representative_name %></h5>
      <%= friend.email %>
    </div>
  </a>
  <% if !defined?(hide_buttons) || !hide_buttons %>
    <% if friend.id == current_user.id %>
      <a href="<%= delete_friend_url(@user) %>" class="friendlist-button bg-danger bg-opacity-25">
        <span>Delete</span>
      </a>
    <% else %>
      <% if current_user.friendship_status(friend) == :friend %>
        <a href="<%= delete_friend_url(friend) %>" class="friendlist-button bg-danger bg-opacity-25">
          <span>Delete</span>
        </a>
      <% elsif current_user.friendship_status(friend) == :invited %>
        <a href="<%= cancel_friend_invite_url(friend) %>" class="friendlist-button bg-warning bg-opacity-25">
          <span>cancel invite</span>
        </a>
      <% elsif current_user.friendship_status(friend) == :requested %>
        <a href="<%= accept_friend_request_url(friend) %>" class="friendlist-button bg-success bg-opacity-25">
          <span>accept request</span>
        </a>
        <a href="<%= decline_friend_request_url(friend) %>" class="friendlist-button bg-warning bg-opacity-25">
          <span>decline request</span>
        </a>
      <% else %>
        <a href="<%= invite_friend_url(friend) %>" class="friendlist-button bg-primary bg-opacity-25">
          <span>send invite</span>
        </a>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="user-container">
  <a href="<%= user_url(user) %>" class="circle">
    <%= image_tag user.avatar if user.avatar.attached? %>
  </a>
  <a href="<%= user_url(user) %>" class="mx-3">
    <h5><%= user.representative_name %></h5>
    <%= user.email %>
  </a>
</div>

app/views/users/friends.html.erb
<% unless @friendships[:friend].empty? %>
  <div class="container bg-light rounded shadow-sm py-2">
    <h2><%= (@user.id == current_user.id ? 'My' : @user.representative_name) %> Friends</h2>
    <div class="list-group">
      <% @friendships[:friend].each do |friendship| %>
        <%= render "users/friendlist_item", friend: friendship.towards_user(@user) %>
      <% end %>
    </div>
  </div>
<% end %>

<% if @user.id == current_user.id %>
  <% unless @friendships[:requested].empty? %>
    <div class="container bg-light rounded shadow-sm py-2 mt-3">
      <h2>Requests</h2>
      <div class="list-group">
        <% @friendships[:requested].each do |friendship| %>
          <%= render "users/friendlist_item", friend: friendship.towards_user(@user) %>
        <% end %>
      </div>
    </div>
  <% end %>
  <% unless @friendships[:invited].empty? %>
    <div class="container bg-light rounded shadow-sm py-2 mt-3">
      <h2>My Invites</h2>
      <div class="list-group">
        <% @friendships[:invited].each do |friendship| %>
          <%= render "users/friendlist_item", friend: friendship.towards_user(@user) %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/profile.html.erb
<div class="profile-container mb-3">
  <h2>Profile <%= @user.representative_name %></h2>
  <div class="d-flex">
    <div class="profile-container-left">
      <div class="profile-container-buttons">
        <%= link_to "Friend list", friends_path %>
        <% if current_user.id == @user.id %>
          <%= link_to "Create Post", new_post_path %>
          <%= link_to "Edit profile", edit_user_registration_path %>
        <% else %>
          <% if @user.friendship_status(current_user) == :friend %>
            <%= link_to "Delete friend", delete_friend_path(@user) %>
          <% elsif @user.friendship_status(current_user) == :invited %>
            <%= link_to "Accept friend", accept_friend_request_path(@user) %>
            <%= link_to "Decline friend", decline_friend_request_path(@user) %>
          <% elsif @user.friendship_status(current_user) == :requested %>
            <%= link_to "Cancel friend invite", cancel_friend_invite_path(@user) %>
          <% else %>
            <%= link_to "Invite friend", invite_friend_path(@user) %>
          <% end %>
          <%= link_to "Send message", dialog_path(@user) %>
        <% end %>
        <% if current_user.id == @user.id %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% end %>
      </div>
      <div class="circle">
        <%= image_tag @user.avatar if @user.avatar.attached? %>
      </div>
    </div>
    <div>
      <table class="table">
        <tbody>
        <tr>
          <td>First name</td>
          <td><%= @user.first_name %></td>
        </tr>
        <tr>
          <td>Last name</td>
          <td><%= @user.last_name %></td>
        </tr>
        <tr>
          <td>Sex</td>
          <td><%= @user.sex_name %></td>
        </tr>
        <tr>
          <td>E-mail</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>Birthday</td>
          <td><%= @user.birthday %></td>
        </tr>
        <tr>
          <td>Last sign in</td>
          <td><%= @user.last_sign_in_at.strftime("%H:%M %d-%m-%Y") unless @user.last_sign_in_at.nil? %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% @user.posts.sort_by(&:created_at).reverse.each do |p| %>
  <%= render "posts/post", post: p, show_author: false %>
<% end %>