config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#feed"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/users/:id", to: "users#profile", as: "user"
  get "/users/:id/friends", to: "users#friends", as: "friends"

  get "/users/:id/delete_friend", to: "users#delete_friend", as: "delete_friend"
  get "/users/:id/cancel_friend_invite", to: "users#cancel_friend_invite", as: "cancel_friend_invite"
  get "/users/:id/invite_friend", to: "users#invite_friend", as: "invite_friend"
  get "/users/:id/accept_friend_request", to: "users#accept_friend_request", as: "accept_friend_request"
  get "/users/:id/decline_friend_request", to: "users#decline_friend_request", as: "decline_friend_request"

  get "/people", to: "static_pages#people"
  get "/feed", to: "static_pages#feed"
  get "/about", to: "static_pages#about"

  resources :posts, only: [:new, :create, :show]
  post "/posts/:id/create_comment", to: "posts#create_comment", as: "create_comment"
  get "/posts/:id/toggle_like", to: "posts#toggle_like", as: "toggle_like"

  get "/dialogs/", to: "dialogs#index"
  get "/dialogs/:id", to: "dialogs#show", as: "dialog"
  post "/dialogs/:id/create_message", to: "dialogs#create_message", as: "create_message"
end

app/controllers/dialogs_controller.rb
class DialogsController < ApplicationController
  def show
    @interlocutor = User.find(params[:id])
    @messages = current_user.dialog_messages(@interlocutor.id)
    @message = Message.new
  end

  def index
    @interlocutors = current_user.interlocutors
  end

  def create_message
    @message = current_user.sent_messages.create(recipient_id: params[:id].to_i,
                                                 body: params[:message][:body])
    redirect_back fallback_location: dialogs_path
  end
end

app/views/dialogs/index.html.erb
<% unless @interlocutors.empty? %>
  <div class="container bg-light rounded shadow-sm py-2">
    <h2>Dialogs</h2>
    <div class="list-group">
      <% @interlocutors.each do |user| %>
        <%= render "users/friendlist_item", friend: user, hide_buttons: true, url: dialog_url(user) %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/dialogs/show.html.erb
<h2>Dialog with <%= @interlocutor.representative_name %></h2>
<% @messages.each do |m| %>
  <div class="container bg-light rounded shadow-sm p-1 my-3">
    <h5>
      <% if m.sender_id == current_user.id %>
        You
      <% else %>
        <%= @interlocutor.representative_name %>
      <% end %>
    </h5>
    <p><%= m.body %></p>
    <div class="text-secondary mt-1" style="font-size: 10px; font-weight: bold;">
      <%= m.created_at.strftime("%H:%M %d-%m-%Y") %>
    </div>
  </div>
<% end %>
<div class="container bg-light rounded shadow-sm py-2 mt-3" style="margin-bottom: 5rem">
  <%= simple_form_for @message, url: create_message_path(@interlocutor) do |f| %>
    <div class="form-inputs">
      <%= f.input :body,
                  required: true,
                  as: :text,
                  label: false %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Send", class: "submit-button" %>
    </div>
  <% end %>
</div>