config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#feed"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/users/:id", to: "users#profile", as: "user"
  get "/users/:id/friends", to: "users#friends", as: "friends"

  get "/users/:id/delete_friend", to: "users#delete_friend", as: "delete_friend"
  get "/users/:id/cancel_friend_invite", to: "users#cancel_friend_invite", as: "cancel_friend_invite"
  get "/users/:id/invite_friend", to: "users#invite_friend", as: "invite_friend"
  get "/users/:id/accept_friend_request", to: "users#accept_friend_request", as: "accept_friend_request"
  get "/users/:id/decline_friend_request", to: "users#decline_friend_request", as: "decline_friend_request"

  get "/people", to: "static_pages#people"
  get "/feed", to: "static_pages#feed"
  get "/about", to: "static_pages#about"

  resources :posts, only: [:new, :create, :show]
  post "/posts/:id/create_comment", to: "posts#create_comment", as: "create_comment"
  get "/posts/:id/toggle_like", to: "posts#toggle_like", as: "toggle_like"

  get "/dialogs/", to: "dialogs#index"
  get "/dialogs/:id", to: "dialogs#show", as: "dialog"
  post "/dialogs/:id/create_message", to: "dialogs#create_message", as: "create_message"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', inverse_of: :posts
  has_and_belongs_to_many :likes,
                          class_name: 'User',
                          join_table: 'likes',
                          foreign_key: 'post_id'
  has_many :comments, dependent: :destroy
  has_one_attached :picture
  # @param user [User]
  def liked?(user)
    like_ids.include?(user.id)
  end

  # @param user [User]
  def toggle_like(user)
    return if user.id == author_id

    if liked?(user)
      likes.delete(user)
    else
      likes << user
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    # @type [Post]
    @post = Post.includes(:author, :likes, comments: [:author]).find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    permitted = params.required(:post).permit(:title, :body, :picture)
    @post = current_user.posts.create(title: permitted[:title], body: permitted[:body], picture: permitted[:picture])
    flash[:notice] = 'Successfully post create'
    redirect_to @post
  end

  def create_comment
    permitted = params.required(:comment).permit(:body)
    @comment = current_user.comments.create(body: permitted[:body], post_id: params[:id].to_i)
    flash[:notice] = 'Successfully add comment'
    redirect_to @comment.post
  end

  def toggle_like
    @post = Post.find(params[:id])
    @post.toggle_like(current_user)
    @post.save
    redirect_back fallback_location: post_path(@post)
  end
end

app/views/posts/_comment.html.erb
<div class="container bg-light rounded shadow-sm py-2 my-2">
  <% if show_parent %>
    <a href="<%= post_url(comment.post) %>" style="text-decoration: none;color: var(--bs-body-color);">
      <h4><%= comment.post.title %></h4>
    </a>
    <hr>
  <% end %>
  <div class="user-container">
    <a href="<%= user_url(comment.author) %>" class="circle">
      <%= image_tag comment.author.avatar if comment.author.avatar.attached? %>
    </a>
    <div class="mx-3">
      <div style="font-weight: 600; margin-bottom: 0.3rem;">
        <a href="<%= user_url(comment.author) %>"><%= comment.author.representative_name %></a>
      </div>
      <div>
        <%= comment.body %>
      </div>
      <div class="text-secondary mt-2" style="font-size: 10px; font-weight: bold;">
        <%= comment.created_at.strftime("%H:%M %d-%m-%Y") %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="post-container">
  <%= render "posts/post_body", post: post %>
  <% if show_author %>
    <hr>
    <%= render "users/user", user: post.author %>
  <% end %>
  <hr>
  <%= render "posts/post_icons", post: post %>
</div>

app/views/posts/_post_body.html.erb
<h3><%= post.title %></h3>
<div class="d-flex">
  <div>
    <%= post.body %>
  </div>
  <%= image_tag post.picture if post.picture.attached? %>
</div>

app/views/posts/_post_icons.html.erb
<div class="icons">
  <div>
    <a href="<%= post_path(post) %>">
      <img src="/image/chat-dots.svg" alt=""/>
    </a>
    <%= post.comments.count %>
  </div>
  <div>
    <% if post.author_id == current_user.id %>
      <img src="/image/heart.svg" alt=""/>
    <% else %>
      <% if post.liked?(current_user) %>
        <a href="<%= toggle_like_url(post) %>">
          <img src="/image/heart-fill.svg" alt=""/>
        </a>
      <% else %>
        <a href="<%= toggle_like_url(post) %>">
          <img src="/image/heart.svg" alt=""/>
        </a>
      <% end %>
    <% end %>
    <%= post.likes.count %>
  </div>
  <div>
    <img src="/image/calendar-check.svg" alt=""/>
    <%= post.created_at.strftime("%H:%M %d-%m-%Y") %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="post-container">
  <h2 align="center">Post creation</h2>
  <div class="container">
    <%= simple_form_for @post do |f| %>
      <div class="form-inputs d-flex gap-1" style="flex-direction: column;">
        <%= f.input :title,
                    required: true %>
        <%= f.input :picture,
                    required: false %>
        <%= f.input :body,
                    required: true,
                    as: :text %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Create", class: "submit-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<%= render "post", post: @post, show_author: true %>
<div class="container" style="padding-left: 3rem;margin-top: 1.5rem;">
  <% unless @post.comments.empty? %>
    <% @post.comments.sort_by(&:created_at).reverse.each do |comment| %>
      <%= render "comment", comment: comment, show_parent: false %>
    <% end %>
  <% end %>

  <div class="container bg-light rounded shadow-sm py-2 mt-3" style="margin-bottom: 5rem">
    <%= simple_form_for @comment, url: create_comment_path(@post) do |f| %>
      <div class="form-inputs">
        <%= f.input :body,
                    required: true,
                    as: :text,
                    label: false %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Comment", class: "submit-button" %>
      </div>
    <% end %>
  </div>
</div>